### ISSUE TITLE
上传地址不存在导致 Web 端上传错误的 BUG

### ISSUE THREAD

**Issue by Lruihao** [cky-thinker/file-share#1]
![image](https://user-images.githubusercontent.com/33419593/143818548-ffd53658-a549-42d8-af44-fc169b04db72.png)
原因：windows 上开的服务，windows 的默认下载地址我修改到了 D 盘
希望增加：
- 修改默认文件存放位置
- 每个文件增加复制地址按钮

（作者有时间的话改改吧，本想自己fork后改的，发现我好像不会哈哈哈😂）

**Comment by cky-thinker** [comment]
已添加上传地址编辑功能
