### ISSUE TITLE
如果端口已经被占用，那么点击开启服务会没有任何反应

### ISSUE THREAD

**Issue by Satomi2333** [cky-thinker/file-share#16]
在cmd中使用命令：netsh interface ipv4 show excludedportrange protocol=tcp，查看被排除的端口，发现默认的端口是不能使用的，这时点击开启服务就会没有任何反应。
建议：如果有报错提示就很友好了，并且如果能够在开启服务之前就可以指定端口号，那么就可以避免这个问题

**Comment by cky-thinker** [comment]
已经将设置按钮移动到最外面，冲突后可以修改端口号
