### ISSUE TITLE
小工具非常好用，希望能够添加以下功能

### ISSUE THREAD

**Issue by zwenc** [cky-thinker/file-share#2]
【建议】
1、分享的单个文件地址支持点击复制，这样方法在ubuntu中通过wget直接下载
2、自定义端口

工具非常好用，非常感谢

**Comment by gouzil** [comment]
关于第一个问题可以使用:
http://ip:端口/download/文件名+后缀

示例：
http://192.168.0.106:5421/download/video.mp4

**Comment by cky-thinker** [comment]
已添加自定义端口功能
