### ISSUE TITLE
速度慢

### ISSUE THREAD

**Issue by myliwenbo** [cky-thinker/file-share#22]
再内外的环境行下下载 4MB 感觉有点怪

**Comment by xiaozhang959** [comment]
哥，是不是哪里出问题了，我这下载都几十m每秒的，老快了

**Comment by cky-thinker** [comment]
影响速度的因素有很多
硬件上的例如：路由支持的带宽、网线支持的带宽、wifi信号问题、以及设备的网卡支持的带宽
软件上的：系统是否对网卡做了限速配置等
