### ISSUE TITLE
希望提供文件夹的下载以及几个小建议

### ISSUE THREAD

**Issue by YBxbxxz** [cky-thinker/file-share#27]
试用了下，配合idm共享电影，速度确实能拉满路由器上限，目前还是有几个小遗憾：
1.手机不能分享文件夹
2.不能直接下载文件夹，希望可以提供支持，下载文件夹时自动打包成zip是比较好使的

**Comment by cky-thinker** [comment]
1和2都是浏览器的限制原因，目前没有好的方案
