### ISSUE TITLE
 只显示127.0.0.1地址，切没有多网卡切换按钮

### ISSUE THREAD

**Issue by levie-vans** [cky-thinker/file-share#4]
![image](https://user-images.githubusercontent.com/66657337/195231928-6a862396-9c68-47a1-bfdf-d2626d6d5ab7.png)

**Comment by cky-thinker** [comment]
麻烦在控制台输入下面的命令：
windows系统cmd输入：ipconfig 
mac系统终端输入：ifconfig
将输出信息提供一下，方便排查问题
