### ISSUE TITLE
只生成本地地址而非局域网ip地址

### ISSUE THREAD

**Issue by sceraser** [cky-thinker/file-share#6]
PS C:\Users\scluy> ipconfig

Windows IP 配置

以太网适配器 以太网:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

以太网适配器 vEthernet (V-NET):

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::5d56:b22d:54fb:1d43%22
   IPv4 地址 . . . . . . . . . . . . : 192.168.2.20
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.2.1

无线局域网适配器 本地连接* 1:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

无线局域网适配器 本地连接* 10:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

以太网适配器 蓝牙网络连接:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

以太网适配器 vEthernet (WSL):

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::d97c:b836:28d7:61c3%28
   IPv4 地址 . . . . . . . . . . . . : 172.29.128.1
   子网掩码  . . . . . . . . . . . . : 255.255.240.0
   默认网关. . . . . . . . . . . . . :

以太网适配器 vEthernet (Default Switch):

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::7c03:2de1:59f7:f74%53
   IPv4 地址 . . . . . . . . . . . . : 172.17.128.1
   子网掩码  . . . . . . . . . . . . : 255.255.240.0
   默认网关. . . . . . . . . . . . . :

**Comment by sceraser** [comment]
开启了hyperV，不知道是不是这个原因导致的网卡变化

**Comment by cky-thinker** [comment]
目前对虚拟网卡进行了过滤，以便显示正常ip地址
